//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты_купившие_новинки
    {
        public System.DateTime Дата_заказа { get; set; }
        public string Наименование_товара { get; set; }
        public int Количество { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Организация { get; set; }
        public string Новинка { get; set; }
    }
}
