//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ремонт
    {
        public int Номер_акта { get; set; }
        public System.DateTime Дата_приемки { get; set; }
        public string Готовность { get; set; }
        public Nullable<System.DateTime> Дата_выдачи { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public Nullable<int> Код_товара { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Заключение { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
