//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Код_заказа { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public decimal Стоимость_доставки { get; set; }
        public int Количество { get; set; }
        public decimal Скидка { get; set; }
        public string Оплата { get; set; }
        public int Код_клиента { get; set; }
        public int Код_сотрудника { get; set; }
        public int Код_товара { get; set; }
        public Nullable<decimal> Сумма_заказа { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
