//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы_клиентов
    {
        public int Код_заказа { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public string Организация { get; set; }
        public string Наименование_товара { get; set; }
        public int Количество { get; set; }
        public decimal Цена { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public string Фамилия { get; set; }
    }
}
