//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи_ОПТ_за_день
    {
        public Nullable<int> Количество_заказов_опт { get; set; }
        public Nullable<decimal> Сумма_продаж { get; set; }
        public string Канал_продаж { get; set; }
    }
}
