//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Результат_сотрудников_за_день
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Должность { get; set; }
        public Nullable<int> Заказы_сотрудников { get; set; }
        public Nullable<decimal> Cумма { get; set; }
        public System.DateTime Дата_заказа { get; set; }
    }
}
