//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товарные_остатки
    {
        public int Код_товара { get; set; }
        public string Наименование_товара { get; set; }
        public int Тов_остаток { get; set; }
        public decimal Цена { get; set; }
    }
}
